{% set name = "pygtail" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  noarch: python
  entry_points:
    - pygtail = pygtail.core:main

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools-scm

  run:
    - python >=3.6

test:
  imports:
    - pygtail

  commands:
    - python -m unittest discover -s pygtail


about:
  home: https://github.com/sarnold/pygtail
  license: LGPL-2.1-or-later
  license_file: ../LICENSE
  summary: Reads log file lines that have not been read
  doc_url: "https://github.com/sarnold/pygtail/blob/main/README.rst"
  dev_url: "https://github.com/sarnold/pygtail"


extra:
  recipe-maintainers:
    - sarnold
